from sqlalchemy import Column, String, Integer, Float, Boolean, JSON
from models.postgres.base import Base

class Weapon(Base):
    __tablename__ = "weapons"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    unique_name = Column(String, unique=True, index=True)
    name = Column(String)
    codex_secret = Column(Boolean, default=False)
    critical_chance = Column(Float)
    critical_multiplier = Column(Float)
    damage_per_shot = Column(JSON)
    description = Column(String)
    fire_rate = Column(Float)
    mastery_req = Column(Integer)
    omega_attenuation = Column(Float)
    proc_chance = Column(Float)
    product_category = Column(String)
    total_damage = Column(Integer)
    accuracy = Column(Float)
    blocking_angle = Column(Integer)
    combo_duration = Column(Integer)
    exclude_from_codex = Column(Boolean)
    follow_through = Column(Float)
    heavy_attack_damage = Column(Integer)
    heavy_slam_attack = Column(Integer)
    heavy_slam_radial_damage = Column(Integer)
    heavy_slam_radius = Column(Integer)
    magazine_size = Column(Integer)
    max_level_cap = Column(Integer)
    multishot = Column(Integer)
    noise = Column(String)
    prime_omega_attenuation = Column(Float)
    range = Column(Float)
    reload_time = Column(Float)
    sentinel = Column(Boolean)
    slam_attack = Column(Integer)
    slam_radial_damage = Column(Integer)
    slam_radius = Column(Integer)
    slide_attack = Column(Integer)
    slot = Column(Integer)
    trigger = Column(String)
    wind_up = Column(Float)
